# -*- coding: utf-8 -*-
"""统一常量入口：重导出既有应用配置，不改变原值。"""
from utils.app_config import (SUBJECT_NAMES, DISPLAY_GRADE_CHOICES, GRADE_CHOICES,
                              DEFAULT_GRADE, DEFAULT_SUBJECT)
from utils.question_service import DIFFICULTY_LABELS

SUBJECTS = SUBJECT_NAMES
GRADES = DISPLAY_GRADE_CHOICES
DIFFICULTY_LEVELS = DIFFICULTY_LABELS
__all__ = ["SUBJECT_NAMES", "DISPLAY_GRADE_CHOICES", "GRADE_CHOICES", "DEFAULT_GRADE",
           "DEFAULT_SUBJECT", "DIFFICULTY_LABELS", "SUBJECTS", "GRADES", "DIFFICULTY_LEVELS"]
